apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: solr-init
        image: mvpsitedockerdemov2.azurecr.io/xp1-solr-init
        env:
        - name: SITECORE_SOLR_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sitecore-solr
              key: sitecore-solr-connection-string.txt
      restartPolicy: Never
  backoffLimit: 5